---
dist: bionic
language: ruby
cache: bundler

addons:
  apt:
    packages:
    - libssl1.0-dev

rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
before_install:
  - gem install bundler -v 2.1.4
  - rm Gemfile.lock
