---
dist: bionic
language: ruby

cache:
  bundler: true
  directories:
    - /home/travis/.rvm/

gemfile:
  - gemfiles/openssl_head.gemfile
  - gemfiles/openssl_2_2.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_2_0.gemfile
  - gemfiles/openssl_default.gemfile

env:
  - LIBSSL=1.1 RB=ruby-head
  - LIBSSL=1.1 RB=2.7.1
  - LIBSSL=1.1 RB=2.6.6
  - LIBSSL=1.1 RB=2.5.8
  - LIBSSL=1.1 RB=2.4.10
  - LIBSSL=1.0 RB=ruby-head
  - LIBSSL=1.0 RB=2.7.1
  - LIBSSL=1.0 RB=2.6.6
  - LIBSSL=1.0 RB=2.5.8
  - LIBSSL=1.0 RB=2.4.10

matrix:
  fast_finish: true
  allow_failures:
    - env: LIBSSL=1.1 RB=ruby-head
    - env: LIBSSL=1.0 RB=ruby-head
    - gemfile: gemfiles/openssl_head.gemfile

before_install:
  - ./script/ci/before_install
